/*
	MUDANÇAS

	- ENSAIO: ADICIONEI QUADRILHA_DATA
	CONSTRAINT FK_QUADRILHA_NOME_ENSAIO FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE

	-GERENCIA_QUADRILHA: MESMO QUE ENSAIO
	CONSTRAINT FK_QUADNGQUAD FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE

	-PAR_APRESENTA_QUADRILHA: MESMO
	CONSTRAINT FK_QUADNOMEPARAPRESQUAD FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE,

*/


/*
DROP TABLE VOLUNTARIO;
DROP TABLE TERCEIRIZADA;
DROP TABLE EMPRESA;
DROP TABLE TOURO_MECANICO;
DROP TABLE KAMIKAZE;
DROP TABLE BRINQUEDO_ESPECIALIDADE;
DROP TABLE ENTRETENIMENTO;
DROP TABLE MILHO_VERDE;
DROP TABLE FOOD_TRUCK;
DROP TABLE FONDUE;
DROP TABLE QUENTAO;
DROP TABLE OUTRO;
DROP TABLE BARRACA_DE_COMIDA_ESPEC;
DROP TABLE ALIMENTACAO;
DROP TABLE BARRACA_DE_ROUPAS;
DROP TABLE BARRACA_DE_VENDAS;
DROP TABLE COMERCIAL;
DROP TABLE VENDA_ITEM;
DROP TABLE ITEM;
DROP TABLE VENDA;
DROP TABLE PAR_APRESENTA_QUADRILHA;
DROP TABLE PAR_PARTICIPOU_ENSAIO;
DROP TABLE PAR;
DROP TABLE MULHER;
DROP TABLE HOMEM;
DROP TABLE INTEGRANTE;
DROP TABLE GERENCIA_SHOW;
DROP TABLE CANCOES;
DROP TABLE APRESENTACAO_SHOW;
DROP TABLE BANDA;
DROP TABLE SHOW_MUSICAL;
DROP TABLE FESTIVAL_DE_INVERNO;
DROP TABLE GERENCIA_QUADRILHA;
DROP TABLE ENSAIO;
DROP TABLE QUADRILHA;
DROP TABLE EVENTOS;
DROP TABLE SETOR_CATEGORIA;
DROP TABLE FESTA_JUNINA;
DROP TABLE FESTA_TEMA;
DROP TABLE COREOGRAFO;
DROP TABLE VOLUNTARIADA;
DROP TABLE INSTITUICAO;
DROP TABLE ATRACAO_LICENCA_TIPO;
DROP TABLE GERENTE;
*/


CREATE TABLE GERENTE (
	NOME VARCHAR2(50),
	CPF CHAR(14),
	ENDERECO CHAR(15),
	TELEFONE CHAR(15),
	CONSTRAINT PK_GERENTE PRIMARY KEY(CPF)
);

CREATE TABLE ATRACAO_LICENCA_TIPO (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	LICENCA CHAR(50),
	TIPO VARCHAR2(20),
	CONSTRAINT PK_ATRACAO_LICENCA_TIPO PRIMARY KEY(NOME, ANO)
);

CREATE TABLE INSTITUICAO (
	NOME VARCHAR2(50),
	CNPJ CHAR(18),
	ENDERECO CHAR(15),
	DESCRICAO VARCHAR2(100),
	CONSTRAINT PK_INSTITUICAO PRIMARY KEY(CNPJ)
);

CREATE TABLE VOLUNTARIADA (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	VALOR_DE_ARRECADACAO NUMBER(8, 2),
	NUMERO_DE_VOLUNTARIOS NUMBER(2),
	CPF_GERENTE CHAR(14),
	CNPJ_INSTITUICAO CHAR(18),

	CONSTRAINT PK_VOLUNTARIADA PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NV FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_CPFGVOL FOREIGN KEY(CPF_GERENTE) REFERENCES GERENTE(CPF) ON DELETE CASCADE,
	CONSTRAINT FK_CNPJINSTVOL FOREIGN KEY(CNPJ_INSTITUICAO) REFERENCES INSTITUICAO(CNPJ) ON DELETE CASCADE
);

CREATE TABLE COREOGRAFO (
	NOME VARCHAR2(50),
	CPF CHAR(14),
	TELEFONE CHAR(15),

	CONSTRAINT PK_COREOGRAFO PRIMARY KEY(CPF)
);

CREATE TABLE FESTA_TEMA (
	DATA DATE,
	TEMA VARCHAR2(20),
	CONSTRAINT PK_FESTA_TEMA PRIMARY KEY(DATA)
);

CREATE TABLE FESTA_JUNINA (
	DATA DATE,
	LOCAL VARCHAR2(15),

	CONSTRAINT PK_FESTA_JUNINA PRIMARY KEY(DATA),

	CONSTRAINT FK_DATAFESJUN FOREIGN KEY(DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE
);

CREATE TABLE SETOR_CATEGORIA (
	LOCALIZACAO CHAR(15),
	CATEGORIA VARCHAR2(20),

	CONSTRAINT PK_SETOR_CATEGORIA PRIMARY KEY(LOCALIZACAO)
);

CREATE TABLE EVENTOS (
	LOCALIZACAO CHAR(15),
	ARRECADACAO_DO_SETOR NUMBER(8, 2),

	CONSTRAINT PK_EVENTOS PRIMARY KEY(LOCALIZACAO),

	CONSTRAINT FK_LOCALEV FOREIGN KEY(LOCALIZACAO) REFERENCES SETOR_CATEGORIA(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE QUADRILHA (
	NOME VARCHAR2(50),
	COREOGRAFO_CPF CHAR(14),
	FESTA_JUNINA_DATA DATE,
	EVENTOS_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_QUADRILHA PRIMARY KEY(NOME, FESTA_JUNINA_DATA),

	CONSTRAINT FK_COREOCPFQUAD FOREIGN KEY(COREOGRAFO_CPF) REFERENCES COREOGRAFO(CPF) ON DELETE CASCADE,
	CONSTRAINT FK_FESJUNDATAQUAD FOREIGN KEY(FESTA_JUNINA_DATA) REFERENCES FESTA_JUNINA(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_EVLOCALQUAD FOREIGN KEY(EVENTOS_LOCALIZACAO) REFERENCES EVENTOS(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE ENSAIO (
	DATA DATE,
	HORA CHAR(5),
	LOCAL VARCHAR2(15),
	QUADRILHA_NOME VARCHAR2(50),
	QUADRILHA_DATA DATE,

	CONSTRAINT PK_ENSAIO PRIMARY KEY(DATA, HORA, LOCAL),

	CONSTRAINT FK_QUADRILHA_NOME_ENSAIO FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE
);

CREATE TABLE GERENCIA_QUADRILHA (
	GERENTE_CPF CHAR(14),
	QUADRILHA_NOME VARCHAR2(50),
	QUADRILHA_DATA DATE,

	CONSTRAINT PK_GERENCIA_QUADRILHA PRIMARY KEY(GERENTE_CPF, QUADRILHA_NOME),

	CONSTRAINT FK_GCPFGQUAD FOREIGN KEY(GERENTE_CPF) REFERENCES GERENTE(CPF) ON DELETE CASCADE,
	CONSTRAINT FK_QUADNGQUAD FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE
);

CREATE TABLE FESTIVAL_DE_INVERNO (
	DATA DATE,
	LOCAL VARCHAR2(15),

	CONSTRAINT PK_FESTIVAL_DE_INVERNO PRIMARY KEY(DATA),

	CONSTRAINT FK_DATAFESINV FOREIGN KEY(DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE
);

CREATE TABLE SHOW_MUSICAL (
	DATA DATE,
	NUMERO_DE_BANDAS NUMBER(2),
	FESTIVAL_DE_INVERNO_DATA DATE,
	EVENTOS_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_SHOW_MUSICAL PRIMARY KEY(DATA),

	CONSTRAINT FK_FESINVDATASHOWM FOREIGN KEY(FESTIVAL_DE_INVERNO_DATA) REFERENCES FESTIVAL_DE_INVERNO(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_EV_LOCAL_SHOWM FOREIGN KEY(EVENTOS_LOCALIZACAO) REFERENCES EVENTOS(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE BANDA (
	NOME VARCHAR2(50),

	CONSTRAINT PK_BANDA PRIMARY KEY(NOME)
);

CREATE TABLE APRESENTACAO_SHOW (
	HORA_DE_INICIO CHAR(5),
	HORA_DE_TERMINO CHAR(5),
	BANDA_NOME VARCHAR2(50),
	SHOW_MUSICAL_DATA DATE,

	CONSTRAINT PK_APRESENTACAO_SHOW PRIMARY KEY(BANDA_NOME, SHOW_MUSICAL_DATA),

	CONSTRAINT FK_BANDNOMEAPRESSHOW FOREIGN KEY(BANDA_NOME) REFERENCES BANDA(NOME) ON DELETE CASCADE,
	CONSTRAINT FK_SHOWMUSDATAAPRESSHOW FOREIGN KEY(SHOW_MUSICAL_DATA) REFERENCES SHOW_MUSICAL(DATA) ON DELETE CASCADE
);

CREATE TABLE CANCOES (
	CANCAO VARCHAR2(20),
	BANDA_NOME VARCHAR2(50),
	SHOW_MUSICAL_DATA DATE,

	CONSTRAINT PK_CANCOES PRIMARY KEY(CANCAO, BANDA_NOME, SHOW_MUSICAL_DATA),

	CONSTRAINT FK_BANDNOMECAN FOREIGN KEY(BANDA_NOME, SHOW_MUSICAL_DATA) REFERENCES APRESENTACAO_SHOW(BANDA_NOME, SHOW_MUSICAL_DATA) ON DELETE CASCADE
);

CREATE TABLE GERENCIA_SHOW (
	GERENTE_CPF CHAR(14),
	SHOW_MUSICAL_DATA DATE,

	CONSTRAINT PK_GERENCIA_SHOW PRIMARY KEY(GERENTE_CPF, SHOW_MUSICAL_DATA),

	CONSTRAINT FK_GCPFGSHOW FOREIGN KEY(GERENTE_CPF) REFERENCES GERENTE(CPF) ON DELETE CASCADE,
	CONSTRAINT FK_SHOWMUSDATAGSHOW FOREIGN KEY(SHOW_MUSICAL_DATA) REFERENCES SHOW_MUSICAL(DATA) ON DELETE CASCADE
);

CREATE TABLE INTEGRANTE (
	NOME VARCHAR2(50),
	CPF CHAR(14),
	INSTRUMENTO VARCHAR2(20),
	BANDA_NOME VARCHAR2(50),

	CONSTRAINT PK_INTEGRANTE PRIMARY KEY(CPF),

	CONSTRAINT FK_BANDNOMEINT FOREIGN KEY(BANDA_NOME) REFERENCES BANDA(NOME) ON DELETE CASCADE
);

CREATE TABLE HOMEM (
	NOME VARCHAR2(50),
	CPF CHAR(14),
	TELEFONE CHAR(15),

	CONSTRAINT PK_HOMEM PRIMARY KEY(CPF)
);

CREATE TABLE MULHER (
	NOME VARCHAR2(50),
	CPF CHAR(14),
	TELEFONE CHAR(15),

	CONSTRAINT PK_MULHER PRIMARY KEY(CPF)
);

CREATE TABLE PAR (
	HOMEM_CPF CHAR(14),
	MULHER_CPF CHAR(14),

	CONSTRAINT PK_PAR PRIMARY KEY(HOMEM_CPF),

	CONSTRAINT FK_HCPFPAR FOREIGN KEY(HOMEM_CPF) REFERENCES HOMEM(CPF) ON DELETE CASCADE,
	CONSTRAINT FK_MCPFPAR FOREIGN KEY(MULHER_CPF) REFERENCES MULHER(CPF) ON DELETE CASCADE
);

CREATE TABLE PAR_PARTICIPOU_ENSAIO (
	PAR_HOMEM_CPF CHAR(14),
	DATA_ENSAIO DATE,
	HORA_ENSAIO CHAR(5),
	LOCAL_ENSAIO CHAR(15),

	CONSTRAINT PK_PAR_PARTICIPOU_ENSAIO PRIMARY KEY(PAR_HOMEM_CPF, DATA_ENSAIO, HORA_ENSAIO, LOCAL_ENSAIO),

	CONSTRAINT FK_PARHCPFPARPARTENS FOREIGN KEY(PAR_HOMEM_CPF) REFERENCES PAR(HOMEM_CPF) ON DELETE CASCADE
);

CREATE TABLE PAR_APRESENTA_QUADRILHA (
	QUADRILHA_NOME VARCHAR2(50),
	QUADRILHA_DATA DATE,
	PAR_HOMEM_CPF CHAR(14),

	CONSTRAINT PK_PAR_APRESENTA_QUADRILHA PRIMARY KEY(QUADRILHA_NOME, PAR_HOMEM_CPF),

	CONSTRAINT FK_QUADNOMEPARAPRESQUAD FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE,
	CONSTRAINT FK_PARHCPFPARAPRESQUAD FOREIGN KEY(PAR_HOMEM_CPF) REFERENCES PAR(HOMEM_CPF) ON DELETE CASCADE
);

CREATE TABLE VENDA (
	NOTA_FISCAL VARCHAR2(50),
	DATA DATE,
	TOTAL_DA_VENDA NUMBER(8, 2),
	VOLUNTARIADA_NOME VARCHAR2(50),
	VOLUNTARIADA_ANO NUMBER(4),

	CONSTRAINT PK_VENDA PRIMARY KEY(NOTA_FISCAL),

	CONSTRAINT FK_VOLNVEN FOREIGN KEY(VOLUNTARIADA_NOME, VOLUNTARIADA_ANO) REFERENCES VOLUNTARIADA(NOME, ANO) ON DELETE CASCADE
);

CREATE TABLE ITEM (
	NOME VARCHAR2(50),
	PRECO NUMBER(5, 2),

	CONSTRAINT PK_ITEM PRIMARY KEY(NOME)	
);

CREATE TABLE VENDA_ITEM (
	ITEM_NOME VARCHAR2(50),
	VENDA_NOTA_FISCAL VARCHAR2(50),
	QUANTIDADE NUMBER(2),

	CONSTRAINT PK_VENDA_ITEM PRIMARY KEY(ITEM_NOME, VENDA_NOTA_FISCAL),

	CONSTRAINT FK_ITNVENDIT FOREIGN KEY(ITEM_NOME) REFERENCES ITEM(NOME) ON DELETE CASCADE,
	CONSTRAINT FK_VENDNOTFISVENDIT FOREIGN KEY(VENDA_NOTA_FISCAL) REFERENCES VENDA(NOTA_FISCAL) ON DELETE CASCADE
);

CREATE TABLE COMERCIAL (
	LOCALIZACAO CHAR(15),
	ARRECADACAO_DO_SETOR NUMBER(8, 2),

	CONSTRAINT PK_COMERCIAL PRIMARY KEY(LOCALIZACAO),

	CONSTRAINT FK_LOCALCOMERC FOREIGN KEY(LOCALIZACAO) REFERENCES SETOR_CATEGORIA(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE BARRACA_DE_VENDAS (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTA_TEMA_DATA DATE,
	COMERCIAL_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_BARRACA_DE_VENDAS PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NBVEND FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESTEMADATABVEND FOREIGN KEY(FESTA_TEMA_DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_COMERCLOCALBVEND FOREIGN KEY(COMERCIAL_LOCALIZACAO) REFERENCES COMERCIAL(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE BARRACA_DE_ROUPAS (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTA_TEMA_DATA DATE,
	COMERCIAL_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_BARRACA_DE_ROUPAS PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NBROUP FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESTEMADATABROUP FOREIGN KEY(FESTA_TEMA_DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_COMERCLOCALBROUP FOREIGN KEY(COMERCIAL_LOCALIZACAO) REFERENCES COMERCIAL(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE ALIMENTACAO (
	LOCALIZACAO CHAR(15),
	ARRECADACAO_DO_SETOR NUMBER(8, 2),

	CONSTRAINT PK_ALIMENTACAO PRIMARY KEY(LOCALIZACAO),

	CONSTRAINT FK_LOCALALIMENT FOREIGN KEY(LOCALIZACAO) REFERENCES SETOR_CATEGORIA(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE BARRACA_DE_COMIDA_ESPEC (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	COMIDA_ESPECIALIDADE VARCHAR2(20),

	CONSTRAINT PK_BCE PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NBCOMESPEC FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE
);

CREATE TABLE OUTRO (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTA_TEMA_DATA DATE,
	ALIMENTACAO_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_OUTRO PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NOUTRO FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESTEMADATAOUTRO FOREIGN KEY(FESTA_TEMA_DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_ALIMENTLOCALOUTRO FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE QUENTAO (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTA_JUNINA_DATA DATE,
	ALIMENTACAO_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_QUENTAO PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NQUENT FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESJUNDATAQUENT FOREIGN KEY(FESTA_JUNINA_DATA) REFERENCES FESTA_JUNINA(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_ALIMENTLOCALQUENT FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE FONDUE (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTIVAL_DE_INVERNO_DATA DATE,
	ALIMENTACAO_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_FONDUE PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NFONDUE FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESINVDATAFONDUE FOREIGN KEY(FESTIVAL_DE_INVERNO_DATA) REFERENCES FESTIVAL_DE_INVERNO(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_ALIMENTLOCALFONDUE FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE FOOD_TRUCK (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTIVAL_DE_INVERNO_DATA DATE,
	ALIMENTACAO_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_FOOD_TRUCK PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NFTRUCK FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESINVDATAFTRUCK FOREIGN KEY(FESTIVAL_DE_INVERNO_DATA) REFERENCES FESTIVAL_DE_INVERNO(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_ALIMENTLOCALFTRUCK FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE MILHO_VERDE (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTA_JUNINA_DATA DATE,
	ALIMENTACAO_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_MILHO_VERDE PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NMIVER FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESJUNDATAMIVER FOREIGN KEY(FESTA_JUNINA_DATA) REFERENCES FESTA_JUNINA(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_ALIMENTLOCALMIVER FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE ENTRETENIMENTO (
	LOCALIZACAO CHAR(15),
	ARRECADACAO_DO_SETOR NUMBER(8, 2),

	CONSTRAINT PK_ENTRETENIMENTO PRIMARY KEY(LOCALIZACAO),

	CONSTRAINT FK_LOCALENTRET FOREIGN KEY(LOCALIZACAO) REFERENCES SETOR_CATEGORIA(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE BRINQUEDO_ESPECIALIDADE (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	ESPECIALIDADE VARCHAR2(20),

	CONSTRAINT PK_BRINQUEDO_ESPECIALIDADE PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NBRINQESPEC FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE
);

CREATE TABLE KAMIKAZE (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTIVAL_DE_INVERNO_DATA DATE,
	ALTURA_MIN NUMBER(3, 2),
	ALTURA_MAX NUMBER(3, 2),
	ENTRETENIMENTO_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_KAMIKAZE PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NKAMI FOREIGN KEY(NOME, ANO) REFERENCES BRINQUEDO_ESPECIALIDADE(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESINVDATAKAMI FOREIGN KEY(FESTIVAL_DE_INVERNO_DATA) REFERENCES FESTIVAL_DE_INVERNO(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_ENTRETLOCALKAMI FOREIGN KEY(ENTRETENIMENTO_LOCALIZACAO) REFERENCES ENTRETENIMENTO(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE TOURO_MECANICO (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	FESTA_JUNINA_DATA DATE,
	ALTURA_MIN NUMBER(3, 2),
	ALTURA_MAX NUMBER(3, 2),
	ENTRETENIMENTO_LOCALIZACAO CHAR(15),

	CONSTRAINT PK_TOURO_MECANICO PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NTOMEC FOREIGN KEY(NOME, ANO) REFERENCES BRINQUEDO_ESPECIALIDADE(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_FESJUNDATATOMEC FOREIGN KEY(FESTA_JUNINA_DATA) REFERENCES FESTA_JUNINA(DATA) ON DELETE CASCADE,
	CONSTRAINT FK_ENTRETLOCALTOMEC FOREIGN KEY(ENTRETENIMENTO_LOCALIZACAO) REFERENCES ENTRETENIMENTO(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE EMPRESA (
	NOME VARCHAR2(50),
	CNPJ CHAR(18),
	TELEFONE CHAR(15),

	CONSTRAINT PK_EMPRESA PRIMARY KEY(CNPJ)
);

CREATE TABLE TERCEIRIZADA (
	NOME VARCHAR2(50),
	ANO NUMBER(4),
	VALOR_DE_ARRECADACAO NUMBER(8, 2),
	CNPJ_EMPRESA CHAR(18),
	CNPJ_INSTITUICAO CHAR(18),
	CPF_GERENTE CHAR(14),
	VALOR_ALUGUEL NUMBER(8, 2),

	CONSTRAINT PK_TERCEIRIZADA PRIMARY KEY(NOME, ANO),

	CONSTRAINT FK_NTERC FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
	CONSTRAINT FK_CNPJEMPTERC FOREIGN KEY(CNPJ_EMPRESA) REFERENCES EMPRESA(CNPJ) ON DELETE CASCADE,
	CONSTRAINT FK_CNPJINSTTERC FOREIGN KEY(CNPJ_INSTITUICAO) REFERENCES INSTITUICAO(CNPJ) ON DELETE CASCADE,
	CONSTRAINT FK_CPFGTERC FOREIGN KEY(CPF_GERENTE) REFERENCES GERENTE(CPF) ON DELETE CASCADE
);

CREATE TABLE VOLUNTARIO (
	NOME VARCHAR2(50),
	CPF CHAR(14),
	TELEFONE CHAR(15),
	VOLUNTARIADA_NOME VARCHAR2(50),
	VOLUNTARIADA_ANO NUMBER(4),

	CONSTRAINT PK_VOLUNTARIO PRIMARY KEY(CPF),

	CONSTRAINT FK_VOLNVOL FOREIGN KEY(VOLUNTARIADA_NOME, VOLUNTARIADA_ANO) REFERENCES VOLUNTARIADA(NOME, ANO) ON DELETE CASCADE
);

/*
LICENCA?????????
HORA????????????
*/