/*
    MUDANÇAS

    - ENSAIO: ADICIONEI QUADRILHA_DATA
    CONSTRAINT FK_QUADRILHA_NOME_ENSAIO FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE

    -GERENCIA_QUADRILHA: MESMO QUE ENSAIO
    CONSTRAINT FK_QUADNGQUAD FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE

    -PAR_APRESENTA_QUADRILHA: MESMO
    CONSTRAINT FK_QUADNOMEPARAPRESQUAD FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE,

*/


/*
DROP TABLE VOLUNTARIO;
DROP TABLE TERCEIRIZADA;
DROP TABLE EMPRESA;
DROP TABLE TOURO_MECANICO;
DROP TABLE KAMIKAZE;
DROP TABLE BRINQUEDO_ESPECIALIDADE;
DROP TABLE ENTRETENIMENTO;
DROP TABLE MILHO_VERDE;
DROP TABLE FOOD_TRUCK;
DROP TABLE FONDUE;
DROP TABLE QUENTAO;
DROP TABLE OUTRO;
DROP TABLE BARRACA_DE_COMIDA_ESPEC;
DROP TABLE ALIMENTACAO;
DROP TABLE BARRACA_DE_ROUPAS;
DROP TABLE BARRACA_DE_VENDAS;
DROP TABLE COMERCIAL;
DROP TABLE VENDA_ITEM;
DROP TABLE ITEM;
DROP TABLE VENDA;
DROP TABLE PAR_APRESENTA_QUADRILHA;
DROP TABLE PAR_PARTICIPOU_ENSAIO;
DROP TABLE PAR;
DROP TABLE MULHER;
DROP TABLE HOMEM;
DROP TABLE INTEGRANTE;
DROP TABLE GERENCIA_SHOW;
DROP TABLE CANCOES;
DROP TABLE APRESENTACAO_SHOW;
DROP TABLE BANDA;
DROP TABLE SHOW_MUSICAL;
DROP TABLE FESTIVAL_DE_INVERNO;
DROP TABLE GERENCIA_QUADRILHA;
DROP TABLE ENSAIO;
DROP TABLE QUADRILHA;
DROP TABLE EVENTOS;
DROP TABLE SETOR_CATEGORIA;
DROP TABLE FESTA_JUNINA;
DROP TABLE FESTA_TEMA;
DROP TABLE COREOGRAFO;
DROP TABLE VOLUNTARIADA;
DROP TABLE INSTITUICAO;
DROP TABLE ATRACAO_LICENCA_TIPO;
*/
DROP TABLE GERENTE;

CREATE TABLE GERENTE (
    NOME VARCHAR(30),
    CPF CHAR(14) NOT NULL,
    ENDERECO VARCHAR(80),
    TELEFONE VARCHAR(15),
    
    CONSTRAINT PK_GERENTE PRIMARY KEY(CPF)
);

CREATE TABLE ATRACAO_LICENCA_TIPO (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    LICENCA CHAR(12) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    
    CONSTRAINT PK_ATRACAO_LICENCA_TIPO PRIMARY KEY(NOME, ANO),
    
    CONSTRAINT CK_ATRACAO_LICENCA CHECK (LICENCA IN ('TERCEIRIZADA', 'VOLUNTARIADA')),
    CONSTRAINT CK_ATRACAO_TIPO CHECK (TIPO IN ('BRINQUEDO', 'COMIDA', 'ROUPAS', 'VENDAS'))
);

CREATE TABLE INSTITUICAO (
    NOME VARCHAR(30),
    CNPJ CHAR(18) NOT NULL,
    ENDERECO VARCHAR(80),
    DESCRICAO VARCHAR(100),
    
    CONSTRAINT PK_INSTITUICAO PRIMARY KEY(CNPJ)
);

CREATE TABLE VOLUNTARIADA (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    VALOR_DE_ARRECADACAO NUMERIC(8, 2) DEFAULT 0,
    NUMERO_DE_VOLUNTARIOS NUMERIC(2) DEFAULT 0,
    CPF_GERENTE CHAR(14) NOT NULL,
    CNPJ_INSTITUICAO CHAR(18) NOT NULL,

    CONSTRAINT PK_VOLUNTARIADA PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NV FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_CPFGVOL FOREIGN KEY(CPF_GERENTE) REFERENCES GERENTE(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_CNPJINSTVOL FOREIGN KEY(CNPJ_INSTITUICAO) REFERENCES INSTITUICAO(CNPJ) ON DELETE CASCADE
);

CREATE TABLE COREOGRAFO (
    NOME VARCHAR(30),
    CPF CHAR(14) NOT NULL,
    TELEFONE CHAR(15),

    CONSTRAINT PK_COREOGRAFO PRIMARY KEY(CPF)
);

CREATE TABLE FESTA_TEMA (
    DATA DATE NOT NULL,
    TEMA CHAR(12) NOT NULL,
    
    CONSTRAINT PK_FESTA_TEMA PRIMARY KEY(DATA),
    
    CONSTRAINT CK_FESTA_TEMA CHECK (TEMA IN ('FESTA_JUNINA', 'FEST_INVERNO'))
);

CREATE TABLE FESTA_JUNINA (
    DATA DATE NOT NULL,
    LOCAL VARCHAR(80),

    CONSTRAINT PK_FESTA_JUNINA PRIMARY KEY(DATA),
    
    CONSTRAINT FK_DATAFESJUN FOREIGN KEY(DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE
);

CREATE TABLE SETOR_CATEGORIA (
    LOCALIZACAO VARCHAR(80) NOT NULL,
    CATEGORIA VARCHAR(20) NOT NULL,

    CONSTRAINT PK_SETOR_CATEGORIA PRIMARY KEY(LOCALIZACAO),
    
    CONSTRAINT CK_CATEGORIA CHECK (CATEGORIA IN ('ALIMENTACAO', 'EVENTOS', 'ENTRETENIMENTO', 'COMERCIAL'))
);

CREATE TABLE EVENTOS (
    LOCALIZACAO VARCHAR(80) NOT NULL,
    ARRECADACAO_DO_SETOR NUMERIC(8, 2) DEFAULT 0,

    CONSTRAINT PK_EVENTOS PRIMARY KEY(LOCALIZACAO),

    CONSTRAINT FK_LOCALEV FOREIGN KEY(LOCALIZACAO) REFERENCES SETOR_CATEGORIA(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE QUADRILHA (
    NOME VARCHAR(30) NOT NULL,
    COREOGRAFO_CPF CHAR(14) NOT NULL,
    FESTA_JUNINA_DATA DATE NOT NULL,
    EVENTOS_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_QUADRILHA PRIMARY KEY(NOME, FESTA_JUNINA_DATA),

    CONSTRAINT FK_COREOCPFQUAD FOREIGN KEY(COREOGRAFO_CPF) REFERENCES COREOGRAFO(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_FESJUNDATAQUAD FOREIGN KEY(FESTA_JUNINA_DATA) REFERENCES FESTA_JUNINA(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_EVLOCALQUAD FOREIGN KEY(EVENTOS_LOCALIZACAO) REFERENCES EVENTOS(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE ENSAIO (
    DATA DATE NOT NULL,
    HORA CHAR(5) NOT NULL,
    LOCAL VARCHAR(80) NOT NULL,
    QUADRILHA_NOME VARCHAR(30) NOT NULL,
    QUADRILHA_DATA DATE NOT NULL,

    CONSTRAINT PK_ENSAIO PRIMARY KEY(DATA, HORA, LOCAL),

    CONSTRAINT FK_QUADRILHA_NOME_ENSAIO FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE
);

CREATE TABLE GERENCIA_QUADRILHA (
    GERENTE_CPF CHAR(14) NOT NULL,
    QUADRILHA_NOME VARCHAR(30) NOT NULL,
    QUADRILHA_DATA DATE NOT NULL,

    CONSTRAINT PK_GERENCIA_QUADRILHA PRIMARY KEY(GERENTE_CPF, QUADRILHA_NOME, QUADRILHA_DATA),

    CONSTRAINT FK_GCPFGQUAD FOREIGN KEY(GERENTE_CPF) REFERENCES GERENTE(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_QUADNGQUAD FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE
);

CREATE TABLE FESTIVAL_DE_INVERNO (
    DATA DATE NOT NULL,
    LOCAL VARCHAR(80),

    CONSTRAINT PK_FESTIVAL_DE_INVERNO PRIMARY KEY(DATA),

    CONSTRAINT FK_DATAFESINV FOREIGN KEY(DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE
);

CREATE TABLE SHOW_MUSICAL (
    DATA DATE NOT NULL,
    NUMERO_DE_BANDAS NUMERIC(2) DEFAULT 0,
    FESTIVAL_DE_INVERNO_DATA DATE NOT NULL,
    EVENTOS_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_SHOW_MUSICAL PRIMARY KEY(DATA),

    CONSTRAINT FK_FESINVDATASHOWM FOREIGN KEY(FESTIVAL_DE_INVERNO_DATA) REFERENCES FESTIVAL_DE_INVERNO(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_EV_LOCAL_SHOWM FOREIGN KEY(EVENTOS_LOCALIZACAO) REFERENCES EVENTOS(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE BANDA (
    NOME VARCHAR(30) NOT NULL,

    CONSTRAINT PK_BANDA PRIMARY KEY(NOME)
);

CREATE TABLE APRESENTACAO_SHOW (
    HORA_DE_INICIO CHAR(5),
    HORA_DE_TERMINO CHAR(5),
    BANDA_NOME VARCHAR(30) NOT NULL,
    SHOW_MUSICAL_DATA DATE NOT NULL,

    CONSTRAINT PK_APRESENTACAO_SHOW PRIMARY KEY(BANDA_NOME, SHOW_MUSICAL_DATA),

    CONSTRAINT FK_BANDNOMEAPRESSHOW FOREIGN KEY(BANDA_NOME) REFERENCES BANDA(NOME) ON DELETE CASCADE,
    CONSTRAINT FK_SHOWMUSDATAAPRESSHOW FOREIGN KEY(SHOW_MUSICAL_DATA) REFERENCES SHOW_MUSICAL(DATA) ON DELETE CASCADE
);

CREATE TABLE CANCOES (
    CANCAO VARCHAR(30) NOT NULL,
    BANDA_NOME VARCHAR(30) NOT NULL,
    SHOW_MUSICAL_DATA DATE NOT NULL,

    CONSTRAINT PK_CANCOES PRIMARY KEY(CANCAO, BANDA_NOME, SHOW_MUSICAL_DATA),

    CONSTRAINT FK_BANDNOMECAN FOREIGN KEY(BANDA_NOME, SHOW_MUSICAL_DATA) REFERENCES APRESENTACAO_SHOW(BANDA_NOME, SHOW_MUSICAL_DATA) ON DELETE CASCADE
);

CREATE TABLE GERENCIA_SHOW (
    GERENTE_CPF CHAR(14) NOT NULL,
    SHOW_MUSICAL_DATA DATE NOT NULL,

    CONSTRAINT PK_GERENCIA_SHOW PRIMARY KEY(GERENTE_CPF, SHOW_MUSICAL_DATA),

    CONSTRAINT FK_GCPFGSHOW FOREIGN KEY(GERENTE_CPF) REFERENCES GERENTE(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_SHOWMUSDATAGSHOW FOREIGN KEY(SHOW_MUSICAL_DATA) REFERENCES SHOW_MUSICAL(DATA) ON DELETE CASCADE
);

CREATE TABLE INTEGRANTE (
    NOME VARCHAR(30),
    CPF CHAR(14) NOT NULL,
    INSTRUMENTO VARCHAR(30),
    BANDA_NOME VARCHAR(30),

    CONSTRAINT PK_INTEGRANTE PRIMARY KEY(CPF),

    CONSTRAINT FK_BANDNOMEINT FOREIGN KEY(BANDA_NOME) REFERENCES BANDA(NOME) ON DELETE SET NULL
);

CREATE TABLE HOMEM (
    NOME VARCHAR(30),
    CPF CHAR(14) NOT NULL,
    TELEFONE CHAR(15),

    CONSTRAINT PK_HOMEM PRIMARY KEY(CPF)
);

CREATE TABLE MULHER (
    NOME VARCHAR(30),
    CPF CHAR(14) NOT NULL,
    TELEFONE CHAR(15),

    CONSTRAINT PK_MULHER PRIMARY KEY(CPF)
);

CREATE TABLE PAR (
    HOMEM_CPF CHAR(14) NOT NULL,
    MULHER_CPF CHAR(14) NOT NULL,

    CONSTRAINT PK_PAR PRIMARY KEY(HOMEM_CPF),

    CONSTRAINT FK_HCPFPAR FOREIGN KEY(HOMEM_CPF) REFERENCES HOMEM(CPF) ON DELETE CASCADE,
    CONSTRAINT FK_MCPFPAR FOREIGN KEY(MULHER_CPF) REFERENCES MULHER(CPF) ON DELETE CASCADE
);

CREATE TABLE PAR_PARTICIPOU_ENSAIO (
    PAR_HOMEM_CPF CHAR(14) NOT NULL,
    ENSAIO_DATA DATE NOT NULL,
    ENSAIO_HORA CHAR(5) NOT NULL,
    ENSAIO_LOCAL VARCHAR(80) NOT NULL,

    CONSTRAINT PK_PAR_PARTICIPOU_ENSAIO PRIMARY KEY(PAR_HOMEM_CPF, ENSAIO_DATA, ENSAIO_HORA, ENSAIO_LOCAL),

    CONSTRAINT FK_PARHCPFPARPARTENS FOREIGN KEY(PAR_HOMEM_CPF) REFERENCES PAR(HOMEM_CPF) ON DELETE CASCADE,
    CONSTRAINT FK_ENSAIOPARPARTENS FOREIGN KEY(ENSAIO_DATA, ENSAIO_HORA, ENSAIO_LOCAL) REFERENCES ENSAIO(DATA, HORA, LOCAL) ON DELETE CASCADE
);

CREATE TABLE PAR_APRESENTA_QUADRILHA (
    QUADRILHA_NOME VARCHAR(30) NOT NULL,
    QUADRILHA_DATA DATE NOT NULL,
    PAR_HOMEM_CPF CHAR(14) NOT NULL,

    CONSTRAINT PK_PAR_APRESENTA_QUADRILHA PRIMARY KEY(QUADRILHA_NOME, QUADRILHA_DATA, PAR_HOMEM_CPF),

    CONSTRAINT FK_QUADNOMEPARAPRESQUAD FOREIGN KEY(QUADRILHA_NOME, QUADRILHA_DATA) REFERENCES QUADRILHA(NOME, FESTA_JUNINA_DATA) ON DELETE CASCADE,
    CONSTRAINT FK_PARHCPFPARAPRESQUAD FOREIGN KEY(PAR_HOMEM_CPF) REFERENCES PAR(HOMEM_CPF) ON DELETE CASCADE
);

CREATE TABLE VENDA (
    NOTA_FISCAL NUMERIC NOT NULL,
    DATA DATE,
    TOTAL_DA_VENDA NUMERIC(8, 2) DEFAULT 0,
    VOLUNTARIADA_NOME VARCHAR(30) NOT NULL,
    VOLUNTARIADA_ANO NUMERIC(4) NOT NULL,

    CONSTRAINT PK_VENDA PRIMARY KEY(NOTA_FISCAL),

    CONSTRAINT FK_VOLNVEN FOREIGN KEY(VOLUNTARIADA_NOME, VOLUNTARIADA_ANO) REFERENCES VOLUNTARIADA(NOME, ANO) ON DELETE CASCADE
);

CREATE TABLE ITEM (
    NOME VARCHAR(30) NOT NULL,
    PRECO NUMERIC(5, 2),

    CONSTRAINT PK_ITEM PRIMARY KEY(NOME)    
);

CREATE TABLE VENDA_ITEM (
    ITEM_NOME VARCHAR(30) NOT NULL,
    VENDA_NOTA_FISCAL NUMERIC NOT NULL,
    QUANTIDADE NUMERIC(2) NOT NULL,

    CONSTRAINT PK_VENDA_ITEM PRIMARY KEY(ITEM_NOME, VENDA_NOTA_FISCAL),

    CONSTRAINT FK_ITNVENDIT FOREIGN KEY(ITEM_NOME) REFERENCES ITEM(NOME) ON DELETE CASCADE,
    CONSTRAINT FK_VENDNOTFISVENDIT FOREIGN KEY(VENDA_NOTA_FISCAL) REFERENCES VENDA(NOTA_FISCAL) ON DELETE CASCADE,
    CONSTRAINT CK_QUANTIDADE CHECK (QUANTIDADE > 0)
);

CREATE TABLE COMERCIAL (
    LOCALIZACAO VARCHAR(80) NOT NULL,
    ARRECADACAO_DO_SETOR NUMERIC(8, 2) DEFAULT 0,

    CONSTRAINT PK_COMERCIAL PRIMARY KEY(LOCALIZACAO),

    CONSTRAINT FK_LOCALCOMERC FOREIGN KEY(LOCALIZACAO) REFERENCES SETOR_CATEGORIA(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE BARRACA_DE_VENDAS (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTA_TEMA_DATA DATE NOT NULL,
    COMERCIAL_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_BARRACA_DE_VENDAS PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NBVEND FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESTEMADATABVEND FOREIGN KEY(FESTA_TEMA_DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_COMERCLOCALBVEND FOREIGN KEY(COMERCIAL_LOCALIZACAO) REFERENCES COMERCIAL(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE BARRACA_DE_ROUPAS (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTA_TEMA_DATA DATE NOT NULL,
    COMERCIAL_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_BARRACA_DE_ROUPAS PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NBROUP FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESTEMADATABROUP FOREIGN KEY(FESTA_TEMA_DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_COMERCLOCALBROUP FOREIGN KEY(COMERCIAL_LOCALIZACAO) REFERENCES COMERCIAL(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE ALIMENTACAO (
    LOCALIZACAO VARCHAR(80) NOT NULL,
    ARRECADACAO_DO_SETOR NUMERIC(8, 2) DEFAULT 0,

    CONSTRAINT PK_ALIMENTACAO PRIMARY KEY(LOCALIZACAO),

    CONSTRAINT FK_LOCALALIMENT FOREIGN KEY(LOCALIZACAO) REFERENCES SETOR_CATEGORIA(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE BARRACA_DE_COMIDA_ESPEC (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    COMIDA_ESPECIALIDADE VARCHAR(20) NOT NULL,

    CONSTRAINT PK_BCE PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NBCOMESPEC FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT CK_COMIDA_ESPECIALIDADE CHECK (COMIDA_ESPECIALIDADE IN ('MILHO', 'QUENTAO', 'FOOD_TRUCK', 'FONDUE', 'OUTRO'))
);

CREATE TABLE OUTRO (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTA_TEMA_DATA DATE NOT NULL,
    ALIMENTACAO_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_OUTRO PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NOUTRO FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESTEMADATAOUTRO FOREIGN KEY(FESTA_TEMA_DATA) REFERENCES FESTA_TEMA(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_ALIMENTLOCALOUTRO FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE QUENTAO (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTA_JUNINA_DATA DATE NOT NULL,
    ALIMENTACAO_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_QUENTAO PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NQUENT FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESJUNDATAQUENT FOREIGN KEY(FESTA_JUNINA_DATA) REFERENCES FESTA_JUNINA(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_ALIMENTLOCALQUENT FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE FONDUE (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTIVAL_DE_INVERNO_DATA DATE NOT NULL,
    ALIMENTACAO_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_FONDUE PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NFONDUE FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESINVDATAFONDUE FOREIGN KEY(FESTIVAL_DE_INVERNO_DATA) REFERENCES FESTIVAL_DE_INVERNO(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_ALIMENTLOCALFONDUE FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE FOOD_TRUCK (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTIVAL_DE_INVERNO_DATA DATE NOT NULL,
    ALIMENTACAO_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_FOOD_TRUCK PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NFTRUCK FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESINVDATAFTRUCK FOREIGN KEY(FESTIVAL_DE_INVERNO_DATA) REFERENCES FESTIVAL_DE_INVERNO(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_ALIMENTLOCALFTRUCK FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE MILHO_VERDE (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTA_JUNINA_DATA DATE NOT NULL,
    ALIMENTACAO_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_MILHO_VERDE PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NMIVER FOREIGN KEY(NOME, ANO) REFERENCES BARRACA_DE_COMIDA_ESPEC(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESJUNDATAMIVER FOREIGN KEY(FESTA_JUNINA_DATA) REFERENCES FESTA_JUNINA(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_ALIMENTLOCALMIVER FOREIGN KEY(ALIMENTACAO_LOCALIZACAO) REFERENCES ALIMENTACAO(LOCALIZACAO) ON DELETE SET NULL
);

CREATE TABLE ENTRETENIMENTO (
    LOCALIZACAO VARCHAR(80),
    ARRECADACAO_DO_SETOR NUMERIC(8, 2) DEFAULT 0,

    CONSTRAINT PK_ENTRETENIMENTO PRIMARY KEY(LOCALIZACAO),

    CONSTRAINT FK_LOCALENTRET FOREIGN KEY(LOCALIZACAO) REFERENCES SETOR_CATEGORIA(LOCALIZACAO) ON DELETE CASCADE
);

CREATE TABLE BRINQUEDO_ESPECIALIDADE (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    ESPECIALIDADE VARCHAR(20) NOT NULL,

    CONSTRAINT PK_BRINQUEDO_ESPECIALIDADE PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NBRINQESPEC FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT CK_BRINQUEDO_ESPECIALIDADE CHECK (ESPECIALIDADE IN ('KAMIKAZE', 'TOURO'))
);

CREATE TABLE KAMIKAZE (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTIVAL_DE_INVERNO_DATA DATE NOT NULL,
    ALTURA_MIN NUMERIC(3, 2) DEFAULT 0,
    ALTURA_MAX NUMERIC(3, 2) DEFAULT 0,
    ENTRETENIMENTO_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_KAMIKAZE PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NKAMI FOREIGN KEY(NOME, ANO) REFERENCES BRINQUEDO_ESPECIALIDADE(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESINVDATAKAMI FOREIGN KEY(FESTIVAL_DE_INVERNO_DATA) REFERENCES FESTIVAL_DE_INVERNO(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_ENTRETLOCALKAMI FOREIGN KEY(ENTRETENIMENTO_LOCALIZACAO) REFERENCES ENTRETENIMENTO(LOCALIZACAO) ON DELETE SET NULL,
    
    CONSTRAINT CK_KAMIKAZE_ALTURA CHECK (ALTURA_MAX == 0 OR ALTURA_MAX >= ALTURA_MIN)
);

CREATE TABLE TOURO_MECANICO (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    FESTA_JUNINA_DATA DATE NOT NULL,
    ALTURA_MIN NUMERIC(3, 2) DEFAULT 0,
    ALTURA_MAX NUMERIC(3, 2) DEFAULT 0,
    ENTRETENIMENTO_LOCALIZACAO VARCHAR(80),

    CONSTRAINT PK_TOURO_MECANICO PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NTOMEC FOREIGN KEY(NOME, ANO) REFERENCES BRINQUEDO_ESPECIALIDADE(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_FESJUNDATATOMEC FOREIGN KEY(FESTA_JUNINA_DATA) REFERENCES FESTA_JUNINA(DATA) ON DELETE CASCADE,
    CONSTRAINT FK_ENTRETLOCALTOMEC FOREIGN KEY(ENTRETENIMENTO_LOCALIZACAO) REFERENCES ENTRETENIMENTO(LOCALIZACAO) ON DELETE SET NULL,
    
    CONSTRAINT CK_TOURO_MECANICO CHECK (ALTURA_MAX == 0 OR ALTURA_MAX >= ALTURA_MIN)
);

CREATE TABLE EMPRESA (
    NOME VARCHAR(30),
    CNPJ CHAR(18) NOT NULL,
    TELEFONE CHAR(15),

    CONSTRAINT PK_EMPRESA PRIMARY KEY(CNPJ)
);

CREATE TABLE TERCEIRIZADA (
    NOME VARCHAR(30) NOT NULL,
    ANO NUMERIC(4) NOT NULL,
    VALOR_DE_ARRECADACAO NUMERIC(8, 2) DEFAULT 0,
    CNPJ_EMPRESA CHAR(18) NOT NULL,
    CNPJ_INSTITUICAO CHAR(18) NOT NULL,
    CPF_GERENTE CHAR(14) NOT NULL,
    VALOR_ALUGUEL NUMERIC(8, 2) DEFAULT 0,

    CONSTRAINT PK_TERCEIRIZADA PRIMARY KEY(NOME, ANO),

    CONSTRAINT FK_NTERC FOREIGN KEY(NOME, ANO) REFERENCES ATRACAO_LICENCA_TIPO(NOME, ANO) ON DELETE CASCADE,
    CONSTRAINT FK_CNPJEMPTERC FOREIGN KEY(CNPJ_EMPRESA) REFERENCES EMPRESA(CNPJ) ON DELETE CASCADE,
    CONSTRAINT FK_CNPJINSTTERC FOREIGN KEY(CNPJ_INSTITUICAO) REFERENCES INSTITUICAO(CNPJ) ON DELETE CASCADE,
    CONSTRAINT FK_CPFGTERC FOREIGN KEY(CPF_GERENTE) REFERENCES GERENTE(CPF) ON DELETE CASCADE
);

CREATE TABLE VOLUNTARIO (
    NOME VARCHAR(30),
    CPF CHAR(14) NOT NULL,
    TELEFONE CHAR(15),
    VOLUNTARIADA_NOME VARCHAR(30),
    VOLUNTARIADA_ANO NUMERIC(4),

    CONSTRAINT PK_VOLUNTARIO PRIMARY KEY(CPF),

    CONSTRAINT FK_VOLNVOL FOREIGN KEY(VOLUNTARIADA_NOME, VOLUNTARIADA_ANO) REFERENCES VOLUNTARIADA(NOME, ANO) ON DELETE SET NULL
);


